Freescale/meta-freescale-3rdparty

- conf/machine/imx7s-warp.conf
- recipes-bsp/broadcom-nvram-config/bcm43430-nvram-config.bb
- recipes-bsp/broadcom-nvram-config/files/imx7s-warp/brcmfmac43430-sdio.txt
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
> imx7s-warp: Add bcm43430 nvram config

- conf/machine/nitrogen8m.conf
Signed-off-by: Troy Kisky <troy.kisky@boundarydevices.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
(cherry picked from commit 8b38f230d4d7cd6c283d75c17eddfbe51eca90a5)
> [thud] : cherry-pick (nitrogen8m: fix build issues due to missing mx8/mx8m)

- conf/machine/imx7s-warp.conf
- recipes-bsp/broadcom-nvram-config/bcm43430-nvram-config.bb
- recipes-bsp/broadcom-nvram-config/files/imx7s-warp/brcmfmac43430-sdio.txt
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
(cherry picked from commit 75de4ee0c22040695d3f27adf6bd30184bc8fffd)
> [thud] : cherry-pick (imx7s-warp: Add bcm43430 nvram config)

- conf/machine/imx6qdl-variscite-som.conf
- recipes-kernel/linux/linux-fslc-lts-4.19.bbappend
- recipes-kernel/linux/linux-fslc-lts-4.19/ccimx6ul/0001-MLK-11719-4-mtd-gpmi-change-the-BCH-layout-setting-f.patch
- recipes-kernel/linux/linux-fslc-lts-4.19/ccimx6ul/0002-cpufreq-imx6q-read-OCOTP-through-nvmem-for-imx6ul-im.patch
- recipes-kernel/linux/linux-fslc-lts-4.19/ccimx6ul/0003-ARM-dts-imx6ul-use-nvmem-cells-for-cpu-speed-grading.patch
- recipes-kernel/linux/linux-fslc-lts-4.19/imx6q-var-som-vsc.dts
- recipes-kernel/linux/linux-fslc-lts-4.19/imx6qdl-var-som.dtsi
Tested with - surprise - VarSOM imx6
> Support stable fslc 4.19

- conf/machine/imx7d-pico.conf
cherry-pick commit from master
Signed-off-by: Joris Offouga <offougajoris@gmail.com>
> imx7d-pico: Update settings for U-Boot 2019.07

- conf/machine/imx6qdl-variscite-som.conf
- recipes-kernel/linux/linux-fslc-lts-4.19.bbappend
- recipes-kernel/linux/linux-fslc-lts-4.19/ccimx6ul/0001-MLK-11719-4-mtd-gpmi-change-the-BCH-layout-setting-f.patch
- recipes-kernel/linux/linux-fslc-lts-4.19/ccimx6ul/0002-cpufreq-imx6q-read-OCOTP-through-nvmem-for-imx6ul-im.patch
- recipes-kernel/linux/linux-fslc-lts-4.19/ccimx6ul/0003-ARM-dts-imx6ul-use-nvmem-cells-for-cpu-speed-grading.patch
- recipes-kernel/linux/linux-fslc-lts-4.19/imx6q-var-som-vsc.dts
- recipes-kernel/linux/linux-fslc-lts-4.19/imx6qdl-var-som.dtsi
* Cherry picked from master
* Tested with https://github.com/Freescale/meta-freescale-3rdparty/pull/32 - thanks @fbertux
> warrior: Variscite VarSOM linux-fslc-lts support

- recipes-bsp/u-boot/u-boot-variscite/0001-Fix-build-with-recent-layers.patch
- recipes-bsp/u-boot/u-boot-variscite_2017.03.bb
Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>
> u-boot-variscite: Fix build for recent layers

- recipes-kernel/linux/linux-congatec_4.9.11.bb
Signed-off-by: Daiane Angolini <daiane.angolini@nxp.com>
> linux-congatec: Add LINUX_VERSION

- recipes-bsp/u-boot/u-boot-script-boundary/boundary-bootscripts-Fix-if-statement-that-set-fdt_f.patch
- recipes-bsp/u-boot/u-boot-script-boundary_2018.07.bb
> u-boot-script-boundary: Fix mainline bootscript

- conf/machine/nitrogen8mm.conf
- recipes-kernel/linux/linux-boundary_5.4.bb
Also add new dtb to nitrogen8mm.conf to support hdmi input functionality.
> linux-boundary: update linux version

- recipes-kernel/linux/linux-gateworks-imx_3.14.bb
Signed-off-by: Daiane Angolini <daiane.angolini@nxp.com>
> linux-gateworks-imx: Add LINUX_VERSION

- recipes-bsp/u-boot/u-boot-qoriq/0001-Remove-redundant-YYLOC-global-declaration.patch
- recipes-bsp/u-boot/u-boot-qoriq/0001-binman-Convert-a-few-tests-to-Python-3.patch
- recipes-bsp/u-boot/u-boot-qoriq/0001-binman-Move-to-use-Python-3.patch
- recipes-bsp/u-boot/u-boot-qoriq/0001-buildman-Convert-to-Python-3.patch
- recipes-bsp/u-boot/u-boot-qoriq/0001-patman-Adjust-command-to-return-strings-instead-of-b.patch
- recipes-bsp/u-boot/u-boot-qoriq/0001-patman-Drop-binary-parameter.patch
- recipes-bsp/u-boot/u-boot-qoriq/0001-patman-Update-command.Run-to-handle-failure-better.patch
- recipes-bsp/u-boot/u-boot-qoriq/0001-pylibfdt-Convert-to-Python-3.patch
- recipes-bsp/u-boot/u-boot-qoriq_2019.10.bb
u-boot-qoriq in meta-freescale has upgraded to 2020.04. The patches for
lx2160acex7 can't be applied on 2020.04.
Restore the 2019.10 recipe to avoid build break.
Signed-off-by: Ting Liu <ting.liu@nxp.com>
> u-boot-qoriq: add 2019.10 recipe

- conf/machine/imx7d-remarkable2.conf
- imx7d-remarkable2.md
- recipes-bsp/u-boot/u-boot-remarkable2/0001-Remove-redundant-YYLOC-global-declaration.patch
- recipes-bsp/u-boot/u-boot-remarkable2/0002-dtc-lexer.lex.c_shipped-Remove-redundant-YYLOC-globa.patch
- recipes-bsp/u-boot/u-boot-remarkable2/0003-reMarkable-Print-output-to-pogo-pins.patch
- recipes-bsp/u-boot/u-boot-remarkable2/0004-reMarkable-Change-kernel-arg-to-use-UART6.patch
- recipes-bsp/u-boot/u-boot-remarkable2/0005-reMarkable-Hard-code-boot-addresses.patch
- recipes-bsp/u-boot/u-boot-remarkable2/0006-reMarkable-Don-t-load-data-from-uboot.env.patch
- recipes-bsp/u-boot/u-boot-remarkable2/0007-HACK-Always-autoboot.patch
- recipes-bsp/u-boot/u-boot-remarkable2/0008-HACK-autoboot-Don-t-boot-from-USB.patch
- recipes-bsp/u-boot/u-boot-remarkable2/0009-HACK-reMarkable-Use-initramfs.patch
- recipes-bsp/u-boot/u-boot-remarkable2_2018.03.bb
- recipes-kernel/linux/linux-remarkable2/0001-zero-sugar-Print-output-on-UART6.patch
- recipes-kernel/linux/linux-remarkable2_4.14.bb
This adds support for booting Linux and userspace on the rM2.
> Add support for the reMarkable2

- recipes-kernel/linux/linux-boundary_4.14.x.bb
Signed-off-by: Chris Dimich <Chris.Dimich@boundarydevices.com>
> linux-boundary: bump revision to 623045d

- conf/machine/imx7d-remarkable2.conf
Signed-off-by: Alistair Francis <alistair@alistair23.me>
> imx7d-remarkable2: Ensure we include the linux-firmware

- recipes-kernel/linux/linux-boundary_5.4.bb
Update to linux version 5.4.110.
> linux-boundary: bump revision to e5cde7b

- conf/machine/apalis-imx6.conf
- conf/machine/cgtqmx6.conf
- conf/machine/colibri-imx6.conf
- conf/machine/colibri-imx6ull.conf
- conf/machine/colibri-imx7-emmc.conf
- conf/machine/colibri-imx7-nand.conf
- conf/machine/colibri-vf.conf
- conf/machine/cubox-i.conf
- conf/machine/imx6dl-riotboard.conf
- conf/machine/imx6q-dms-ba16.conf
- conf/machine/imx6qdl-pico.conf
- conf/machine/imx6qdl-variscite-som.conf
- conf/machine/imx6sl-warp.conf
- conf/machine/imx6ul-kontron.conf
- conf/machine/imx6ul-pico.conf
- conf/machine/imx7d-pico.conf
- conf/machine/imx7d-remarkable2.conf
- conf/machine/imx7s-warp.conf
- conf/machine/include/imx233-olinuxino.inc
- conf/machine/nitrogen6sx.conf
- conf/machine/nitrogen6x-lite.conf
- conf/machine/nitrogen6x.conf
- conf/machine/nitrogen7.conf
- conf/machine/nitrogen8m.conf
- conf/machine/nitrogen8mm.conf
- conf/machine/nitrogen8mn.conf
- conf/machine/nitrogen8mp.conf
- conf/machine/ventana.conf
- conf/machine/wandboard.conf
> machines: Adjust for new location of tune files in core

- conf/machine/apalis-imx6.conf
Signed-off-by: Samuli Piippo <samuli.piippo@qt.io>
> apalis-imx6: add missing space to append

- recipes-bsp/libmcc/libmcc_1.05.1.bb
- recipes-bsp/mqxboot/mqxboot_1.0.1.bb
- recipes-bsp/u-boot/u-boot-boundary-common_2020.10.inc
- recipes-bsp/u-boot/u-boot-gateworks-imx_2015.04.bb
- recipes-bsp/u-boot/u-boot-kontron_2020.01.bb
- recipes-bsp/u-boot/u-boot-qoriq_2019.10.bb
- recipes-bsp/u-boot/u-boot-remarkable2_2018.03.bb
- recipes-bsp/u-boot/u-boot-script-gateworks-imx.bb
- recipes-bsp/u-boot/u-boot-timesys_2011.12.bb
- recipes-bsp/u-boot/u-boot-toradex_2020.07.bb
- recipes-bsp/u-boot/u-boot-variscite_2018.03.bb
- recipes-connectivity/ti-18xx-wlconf/ti-18xx-wlconf_8.7.3..bb
- recipes-kernel/kernel-module-mcc-toradex/kernel-module-mcc-toradex_1.06+toradex2.bb
- recipes-kernel/linux/linux-boundary_5.10.bb
> recipes: Use SPDX naming scheme for LICENSE field

- README
Signed-off-by: Luan Rafael Carneiro <luan.rafael@ossystems.com.br>
> README: Change readme to refers kirkstone release

- recipes-kernel/linux/linux-boundary_5.15.bb
> linux-boundary: Upgrade to 5.15

- recipes-kernel/linux/linux-boundary_5.15.bb
> Backport to Kirkstone: linux-boundary: Upgrade to 5.15

- recipes-kernel/linux/linux-boundary_5.10.bb
Changelog:
- most notably fixes issue with suspend functionality
> linux-boundary: bump revision to d50fa514

- recipes-kernel/linux/linux-boundary_5.10.bb
Fixes issue where kernel will hang.
> linux-boundary: bump revision to e6b2f026

- recipes-bsp/u-boot/u-boot-boundary-common_2020.10.inc
- recipes-kernel/linux/linux-boundary_5.10.bb
Mainly to support custom device trees and defconfigs.
> linux-boundary and u-boot-boundary bump revisions

- recipes-kernel/linux/linux-boundary_5.15.bb
> linux-boundary: bump revision to b2f34070

- recipes-kernel/linux/linux-boundary_6.1.bb
> linux-boundary: Upgrade to 6.1

- conf/machine/nitrogen8m.conf
No longer supported defconfig.
> nitrogen8m: remove 3g UBOOT_CONFIG

- conf/machine/nitrogen8mp.conf
Nitrogen 8MP SMARC rpmsg version.
> nitrogen8mp: add devicetree

- recipes-kernel/linux/linux-boundary_6.1.bb
> linux-boundary: bump revision to 7c4b671a
