conf/machine/colibri-vf.conf

SERIAL_CONSOLE would otherwise stay at the default setting as defined in imx-base.inc but this setting would make it try to spawn a getty on a non-existing device on the colibri-vf and login on the UART console would not work. Fixes #5

colibri-vf: use strong assignment of SERIAL_CONSOLE, fixes #5

---

recipes-bsp/u-boot/u-boot-gateworks-imx_2015.04.bb

Add the git repository in the recipe in order to build u-boot for
Gateworks imx6 boards.
Signed-off-by: Sandra Tobajas <sandra.tobajas@savoirfairelinux.com>

u-boot-gateworks-imx: fix recipe building

---

recipes-bsp/u-boot/u-boot-gateworks-imx_2015.04.bb

Bitbake assignments cannnot be non-quoted on RHS, fixes parsing errors
Parsing recipes...ERROR: ParseError at
/mnt/jenkins/workspace/yocto-world-glibc/sources/meta-freescale-3rdparty/recipes-bsp/u-boot/u-boot-gateworks-imx_2015.04.bb:13:
unparsed line: 'S = ${WORKDIR}/git'
Cc: Sandra Tobajas <sandra.tobajas@savoirfairelinux.com>

u-boot-gateworks-imx: Fix parsing errors

---

conf/layer.conf

If you want to use theses branches, use the respective platform.

conf/layer.conf: Drop sumo and thud support

---

conf/machine/imx7s-warp.conf

Since DM conversion, we have to adjust the binary name.
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

imx7s-warp: Update settings to use U-Boot 2019.04

---

conf/machine/include/ccimx6ulsom.inc
recipes-core/init-ifupdown/init-ifupdown/ccimx6ulsbcexpress/interfaces
recipes-core/init-ifupdown/init-ifupdown/ccimx6ulsbcpro/interfaces
recipes-core/udev/udev-rules-digi.bb
recipes-core/udev/udev-rules-digi/ccimx6ul/81-qcom-bt.rules
recipes-core/udev/udev-rules-digi/ccimx6ul/81-qcom-wifi.rules
recipes-core/udev/udev-rules-digi/ccimx6ul/qca6564-attach.sh
recipes-core/udev/udev-rules-digi/ccimx6ul/qca6564-init-wifi.sh
recipes-kernel/kernel-modules/kernel-module-qca6564/modprobe-qca6564.conf
recipes-kernel/kernel-modules/kernel-module-qca6564_git.bb
recipes-kernel/linux-firmware-qca6564/linux-firmware-qca6564_2.4-r2.2.bb
recipes-kernel/linux/linux-fslc/ccimx6ul/0002-ARM-dts-imx6ul-ccimx6ulsom-Add-empty-wireless-and-bl.patch
recipes-kernel/linux/linux-fslc/ccimx6ul/0003-net-wireless-Export-regulatory_hint_user.patch
recipes-kernel/linux/linux-fslc/ccimx6ul/0004-net-wireless-Allow-for-firmware-to-handle-DFS.patch
recipes-kernel/linux/linux-fslc/ccimx6ul/0005-net-wireless-Add-cfg80211_is_gratuitous_arp_unsolici.patch
recipes-kernel/linux/linux-fslc/ccimx6ul/0006-linux-crypto-caam-set-hwrng-quality.patch
recipes-kernel/linux/linux-fslc_%.bbappend

The ConnectCore 6UL SOM contains a Qualcomm QCA6564A chipset with the following features:
- Dual Band 5GHz 802.11ac or 2.4/5GHz 802.11n Wireless Local Area Network (US regulatory domain)
- Open, Wi-Fi Protected Access (WPA) and Wi-Fi Protected Access 2 (WPA2 (personal and enterprise) authentications
- Data encryption using Advanced Encryption Standard (AES) or Temporal Key Integrity Protocol (TKIP)
- Station and SoftAP concurrent modes
- Bluetooth (BT) 4.2
This commit adds software support for it.

pr/ccimx6ul qca6564: Add wireless support for ConnectCore 6UL SOM and SBCs

---

recipes-kernel/kernel-modules/kernel-module-qca6564_git.bb

Update the SRCREV to fix compilation errors with the newest linux-fslc kernel in meta-freescale.

kernel module qca6564: Fix compilation for kernels >= v5.1

---

conf/machine/imx7d-pico.conf

Since DM conversion, we have to adjust the binary name.
Also changes wks file for fix generation image
This PR depends on https://github.com/Freescale/meta-freescale/pull/128
Signed-off-by: Joris Offouga <offougajoris@gmail.com>

imx7d-pico: Update settings for U-Boot 2019.07

---

conf/machine/cgtqmx6.conf
conf/machine/cubox-i.conf
conf/machine/imx6qdl-variscite-som.conf
conf/machine/imx6ul-pico.conf
conf/machine/wandboard.conf

meta-freescale commit 6be9d197386b5c3bd72023981df805d42f87684c
renamed imx-uboot-spl-bootpart.wks to imx-uboot-spl-bootpart.wks.in
The .in extension in wks files allows bitbake variables to be used in
kickstarter files. Set WKS_FILES for all machines to match this new
filename.

Fix WKS_FILE to use files with .in extension

---

conf/machine/apalis-imx6.conf
conf/machine/colibri-imx6.conf

The "KERNEL_DEVICETREE_use-mainline-bsp +=" would override any other
assignment like:
- "KERNEL_DEVICETREE +="
- "KERNEL_DEVICETREE ="
- "KERNEL_DEVICETREE ?="
- "KERNEL_DEVICETREE ??="
change it to "_append" could fix the problem.
Signed-off-by: Ming Liu <liu.ming50@gmail.com>

meta: change "+=" to "_append" for use-mainline-bsp overrides

---

conf/machine/apalis-imx6.conf

At least since 4.14 all device trees are available in upsteram Linux
as well so drop the unnecessary use-mainline-bsp override.
Signed-off-by: Stefan Agner <stefan.agner@toradex.com>

apalis-imx6: build all device trees available upstream

---

conf/machine/colibri-imx6.conf

A regress was introduced by me in commit 9a96fb93:
[ meta: change "+=" to "_append" for use-mainline-bsp overrides ]
a "+=" operator was changed to "_append" in that commit which is wrong
because that makes some non-existing dtb files being put into
KERNEL_DEVICETREE, hence leads build issue for mainline kernel.
Drop the "_append", change "+=" to "=" would be enough.
Signed-off-by: Ming Liu <liu.ming50@gmail.com>

colibri-imx6.conf: drop _append overrides

---

recipes-bsp/u-boot/u-boot-boundary-common_2018.07.inc

In upstream openembedded-core, the definition for the B variable moved from
u-boot.inc to u-boot-common.inc. None of the recipes in this layer use
upstream's u-boot-common.inc, so add the B to the *common* include files here
so u-boot continues to build. See:
http://cgit.openembedded.org/openembedded-core/commit/meta/recipes-bsp/u-boot?id=26023b6b0f897842fd98b3e10a8acd5b3ad8f418&h=master
Fixes:
meta-freescale-3rdparty/recipes-bsp/u-boot/u-boot-boundary_2018.07.bb:do_compile) failed with exit code '1'
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

u-boot-boundary: add "B" to u-boot-boundary-common_2018.07.inc

---

recipes-kernel/linux/linux-boundary/0001-Compiler-Attributes-add-support-for-__copy-gcc-9.patch
recipes-kernel/linux/linux-boundary/0002-include-linux-module.h-copy-__init-__exit-attrs-to-i.patch
recipes-kernel/linux/linux-boundary_4.14.x.bb

These patches are originally from meta-freescale, commit 075681e8 , and
were modified slightly to apply to kernel 4.14.
This fixes errors while building other modules, especially
kernel-module-imx-gpu-viv, which otherwise produces compile errors like:
| [...]tmp/work-shared/nitrogen8m/kernel-source/include/linux/module.h:131:6: error: 'init_module' specifies less restrictive attribute than its target 'gpu_init': 'cold' [-Werror=missing-attributes]
|   131 |  int init_module(void) __attribute__((alias(#initfn)));
|       |      ^~~~~~~~~~~
| [...]tmp/work/nitrogen8m-poky-linux/kernel-module-imx-gpu-viv/6.4.0.p1.0-r0/git/src/hal/os/linux/kernel/gc_hal_kernel_driver.c:1445:1: note: in expansion of macro 'module_init'
|  1445 | module_init(gpu_init);
|       | ^~~~~~~~~~~
| …

linux-boundary: Fix GCC9 compiler attribute related compile errors

---

conf/layer.conf

BBFILE_COLLECTIONS was using the old layer name, rename to match
the new name.

conf/layer.conf: Rename BBFILE_COLLECTIONS to match layer name

---

conf/machine/colibri-imx6ull.conf
conf/machine/colibri-imx7-nand.conf
recipes-bsp/u-boot/u-boot-toradex_2019.07.bb

This fixes build of U-Boot.
The make target u-boot-nand.imx no longer exists u-boot-toradex_2019.07.
Change to the existing build target u-boot.imx and create u-boot-nand.imx in do_configure.

u-boot-toradex: build nand padded binary

---

conf/machine/apalis-imx6.conf
conf/machine/colibri-imx6.conf
conf/machine/colibri-imx6ull.conf
conf/machine/colibri-imx7-nand.conf
conf/machine/colibri-vf.conf
recipes-bsp/u-boot/u-boot-toradex_2019.07.bb

The update from 2016.11 to 2019.07 requires updates in the machine files.
This makes all Toradex machines build again, including colibri-vf.
Tested with colibri-imx6 & colibri-vf with "fslc-x11" and fsl-image-multimedia-full.

Follow u-boot-toradex update

---

recipes-bsp/u-boot/u-boot-script-toradex_2019.07.bb

This helps in making it layer work in multi-bsp environment
Fixes double staging errors like
DEBUG: Staging files from TOPDIR/build/tmp/work/raspberrypi4-yoe-linux-gnueabi/u-boot-script-toradex/2019.07-r0/deploy-u-boot-script-toradex to TOPDIR/build/tmp/deploy/images/raspberrypi4
ERROR: The recipe u-boot-script-toradex is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
TOPDIR/build/tmp/deploy/images/raspberrypi4/boot.scr
(matched in manifest-raspberrypi4-rpi-u-boot-scr.deploy)
Please verify which recipe should provide the above files.
Cc: Max Krummenacher <max.krummenacher@toradex.com>

u-boot-script-toradex: Limit visibility to toradex machines

---

recipes-bsp/u-boot/u-boot-script-toradex_2019.07.bb

u-boot-script-toradex_2019.07.bb: Fix typo in COMPATIBLE_MACHINE

---

conf/machine/imx6qdl-pico.conf
conf/machine/imx6ul-pico.conf
conf/machine/imx7d-pico.conf
conf/machine/imx7s-warp.conf
conf/machine/wandboard.conf

We now choose the BSP in a generic way and this commit changes the
machines to use the new mechanism setting it to mainline one.
Following changes are changed:
- imx6qdl-pico
- imx6ul-pico
- imx7d-pico
- imx7s-warp
- wandboard
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

Use new BSP choosing method for mainline based machines

---

conf/machine/nitrogen8mn.conf

There are compilation errors when building bootloader. Temporarily remove and will be fixed at later date.

Temporarily remove bootloader in Nitrogen8M Nano

---

conf/machine/nitrogen8m.conf
conf/machine/nitrogen8mm.conf
conf/machine/nitrogen8mn.conf

This fixes the following build error:
> Error, the PACKAGE_ARCHS variable (all any noarch ${PACKAGE_EXTRA_ARCHS_tune-cortexa53-crypto} nitrogen8m) for DEFAULTTUNE (cortexa53-crypto) does not contain TUNE_PKGARCH (${@bb.utils.contains('TUNE_FEATURES', 'aarch64', 'aarch64', '${ARMPKGARCH_tune-cortexa53-crypto}' ,d)}).Toolchain tunings invalid:
> Tuning 'cortexa53-crypto' has no defined features, and cannot be used.
Signed-off-by: Carlos Rafael Giani <crg7475@mailbox.org>

nitrogen8*: Include tune-cortexa53.inc instead of generic arch-arm64.inc

---

recipes-kernel/linux/linux-boundary_4.14.x.bb

linux-imx.inc now inherits kernel-yocto class, so LINUX_VERSION must be
defined and also define KBUILD_DEFCONFIG to inform the class to use
boundary source tree defconfig.

linux-boundary: add support for inherited kernel-yocto class

---

conf/machine/colibri-imx7-emmc.conf
conf/machine/colibri-imx7-nand.conf
conf/machine/colibri-vf.conf
recipes-kernel/linux/linux-toradex_4.4.bb

We need to support both mainline and NXP BSP support, to allow that we
need:
- split generic and NXP BSP specific device trees
- avoid setting the default Linux kernel if we use mainline BSP
This was applied for:
- colibri-imx7-emmc
- colibri-imx7-nand
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

colibri-imx7: Fix mainline and NXP BXP support

---

conf/machine/colibri-vf.conf

The imx specific weston version which is otherwise set is not in
COMPATIBLE_MACHINE for Vybrids.
Prevents:
| NOTE: preferred version 8.0.0.imx of weston not available (for item weston)
| NOTE: versions of weston available: 8.0.0
Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>

colibri-vf: set preferred version for weston

---

recipes-bsp/u-boot/u-boot-kontron_2020.01.bb

This commit includes the following changes:
- 3d58441adf3 kontron_mx6ul: Use the SPI NOR as primary boot device to load U-Boot proper
- f1db3d8504b kontron_mx6ul: Use 64K offset for U-Boot proper image, in SPI NOR
- e1d78d738c6 kontron_mx6ul: Fix support for SPI NOR boot
- c5e0df84780 kontron_mx6ul: Enable SPI NAND support

u-boot-kontron: Bump revision to 3d58441adf3

---

recipes-bsp/u-boot/u-boot-variscite_2017.03.bb

Yes it's time to upgrade u-boot-variscite but:
* am very busy keeping things working and a new version requires resources unavailable currently
* once [1] gets applied to oe-core's dunfell, we can backport this series to dunfell
[1] https://lists.openembedded.org/g/openembedded-core/message/139646

u-boot-variscite build fixes

---

recipes-kernel/linux/linux-boundary_5.4.bb

Based on NXP imx_5.4.24_2.1.0 release.
Includes latest stable releases, hence 5.4.x naming.
Includes support for all Boundary Devices platforms + accessories.

linux-boundary: add 5.4.50 recipe

---

recipes-bsp/u-boot/u-boot-boundary-common_2018.07.inc

LPDDR4 init updates
Android security features enabled
Fixed env import
Enabled HAB for i.MX 8M family
Fixed Nano board support
Fixed build with GCC10
Fixed i.MX 8M Mini ARM PLL choice

u-boot-boundary: Bump revision to eae0188

---

recipes-bsp/alsa-state/alsa-state.bbappend
recipes-bsp/alsa-state/files/cubox-i/asound.conf

Fix /etc/asound.conf and enable sound out of the box with the
default machine configurations for cubox-i and hummingboard.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

alsa-state.bbappend: Fix asound.conf for cubox-i

---

recipes-bsp/u-boot/u-boot-boundary_2018.07.bb

As this now conflicts with imx-boot which already does it.
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>

u-boot-boundary: do not install mkimage_uboot any longer

---

conf/machine/nitrogen6sx.conf
conf/machine/nitrogen6x-lite.conf
conf/machine/nitrogen6x.conf
conf/machine/nitrogen7.conf
conf/machine/nitrogen8m.conf
conf/machine/nitrogen8mm.conf
conf/machine/nitrogen8mn.conf

Set a weak assignment for IMX_DEFAULT_BSP before include the
imx-base.inc to allow override IMX_DEFAULT_BSP in local.conf file.

Allow override IMX_DEFAULT_BSP for Nitrogen machines

---

recipes-bsp/u-boot/u-boot-boundary-common_2018.07.inc
recipes-kernel/linux/linux-boundary_4.14.x.bb

Some customers are still on zeus and would like to get the latest rev of kernel/uboot.

[zeus] update 4.14 kernel and 2018.07 uboot

---

recipes-kernel/linux/linux-boundary_5.4.bb

Update to linux version 5.4.90.
Signed-off-by: Chris Dimich <Chris.Dimich@boundarydevices.com>

linux-boundary: update to version 5.4.90

---

README

Old link is not accessible anymore and return 404.
Update README to point to correct mailing list URL.
Fixes: #107 ("Mailing list link in README is a dead link")
Signed-off-by: Andrey Zhizhikin <andrey.z@gmail.com>

README: update link of mailing list

---

conf/machine/imx6qdl-pico.conf
conf/machine/imx6ul-pico.conf
conf/machine/imx7d-pico.conf

We must force the bootloader to `u-boot-fslc` if this was set by a distro.

imx-pico: Pico only supports the u-boot-fslc bootloader 

---

conf/machine/include/imx233-olinuxino.inc

A change was made to meta-freescale to change how the bootloader was being
selected:
https://github.com/Freescale/meta-freescale/pull/696
As a result the choosing logic for the olinuxino MACHINEs was updated to
match.
Build tested for:
- imx233-olinuxino-maxi
- imx233-olinuxino-micro
- imx233-olinuxino-mini
- imx233-olinuxino-nano
Run tested on:
- imx233-olinuxino-maxi
Signed-off-by: Trevor Woerner <twoerner@gmail.com>

olinuxino: update U-Boot choosing

---

recipes-kernel/linux/linux-boundary_5.4.bb

Update to linux version 5.4.110.

Backport to gatesgarth: linux-boundary: bump revision to e5cde7b

---

conf/machine/imx6qdl-pico.conf

On the imx6qdl-pico boards the console is provided by the
UART1 pins, so change it to ttymxc0.
Signed-off-by: Fabio Estevam <festevam@gmail.com>

imx6qdl-pico: Fix the serial console port

---

conf/machine/imx6qdl-pico.conf

Add QCA9377 Wifi support.
Tested on a imx6dl-pico-pi board by doing:
ifconfig wlan0 up
iw dev wlan0 connect ACCESSPOINTNAME
wpa_passphrase ACCESSPOINTNAME > /etc/wpa.conf
(enter the wifi password and press enter)
wpa_supplicant -Dwext -iwlan0 -c /etc/wpa.conf &
udhcpc -i wlan0
ping google.com
Signed-off-by: Fabio Estevam <festevam@gmail.com>

imx6qdl-pico: Add QCA9377 Wifi support

---

conf/machine/imx6qdl-pico.conf

Remove the duplicate MACHINE_FEATURES entry.
There is a more complete one a few lines below.
Signed-off-by: Fabio Estevam <festevam@gmail.com>

imx6qdl-pico: Remove duplicate MACHINE_FEATURES entry

---

conf/machine/imx6qdl-pico.conf

The following commits were cherry-picked from master:
imx6qdl-pico: Fix the serial console port (e253f15)
imx6qdl-pico: Add QCA9377 Wifi support (5f6c423)
imx6qdl-pico: Remove duplicate MACHINE_FEATURES entry (35acd10)

Backport: Fix serial port, add QCA9377 Wifi support to imx6qdl-pico [to hardknott]

---

conf/machine/imx6qdl-pico.conf

The following commits were cherry-picked from master:
imx6qdl-pico: Fix the serial console port (e253f15)
imx6qdl-pico: Add QCA9377 Wifi support (5f6c423)
imx6qdl-pico: Remove duplicate MACHINE_FEATURES entry (35acd10)

Backport: Fix serial port, add QCA9377 Wifi support to imx6qdl-pico [to gatesgarth]

---

recipes-bsp/u-boot/u-boot-toradex-common.inc
recipes-kernel/linux/linux-toradex_4.4.bb

Update U-Boot 2020.07 to latest and Linux kernel to 4.4.274 which fixes some issues a customer reported in trying to build for Colibri VF50/VF61. Thanks!

Update U-Boot 2020.07 and Linux Kernel 4.4.274 Fixing Vybrid

---

conf/machine/nitrogen8mp.conf

Otherwise imx-boot will not compile.

nitrogen8mp: define variables needed for imx-boot recipe

---

conf/machine/nitrogen8mp.conf

Otherwise imx-boot will not compile.

hardknott: nitrogen8mp: define variables needed for imx-boot recipe (backport)

---

recipes-bsp/imx-atf/imx-atf-boundary_2.3.bb
recipes-bsp/u-boot/u-boot-boundary-common_2020.10.inc
recipes-bsp/u-boot/u-boot-gateworks-imx_2015.04.bb
recipes-bsp/u-boot/u-boot-remarkable2_2018.03.bb
recipes-bsp/u-boot/u-boot-timesys_2011.12.bb
recipes-bsp/u-boot/u-boot-variscite_2018.03.bb
recipes-connectivity/ti-18xx-wlconf/ti-18xx-wlconf_8.7.3..bb
recipes-kernel/kernel-module-mcc-toradex/kernel-module-mcc-toradex_1.06+toradex2.bb
recipes-kernel/linux/linux-boundary_5.10.bb
recipes-kernel/linux/linux-gateworks-imx_3.14.bb
recipes-kernel/linux/linux-remarkable2_5.4.bb
recipes-kernel/linux/linux-variscite_4.14.bb

Due to https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
it is required to use https protocol for github repo accessing.
Update created with oe-core/scripts/contrib/convert-srcuri.py (see [0])
[0] - https://git.openembedded.org/openembedded-core/tree/scripts/contrib/convert-srcuri.py
Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>

recipes: use https protocol and add explicit branch parameter

---

recipes-kernel/linux/linux-boundary_5.10.bb

Changelog:
- update to 5.10.72
- more displays supported for i.MX8MP
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>

linux-boundary: bump revision to acef1311

---

conf/machine/colibri-imx6ull.conf

Fix mistype in colibri-imx6ull machine include file when using nxp bsp.
Reported-by: Tomas Vilda
Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>

colibri-imx6ull: fix mistyped override

---

conf/machine/imx7d-remarkable2.conf

This is a workaround to successfully finish the building.
Signed-off-by: Vinicius Aquino <vinicius.aquino@ossystems.com.br>

imx7d-remarkable2: Remove bcm4345* firmwares as it has no providers

---

conf/machine/nitrogen8mp.conf

This commit solves the lack of a provider for 'imx-boot' due to nitrogen8mp not present in COMPATIBLE_MACHINE.
Signed-off-by: Vinicius Aquino <vinicius.aquino@ossystems.com.br>

nitrogen8mp: Define nxp as default BSP

---

conf/machine/apalis-imx6.conf
conf/machine/colibri-imx6.conf
conf/machine/colibri-imx6ull.conf
conf/machine/cubox-i.conf
conf/machine/imx6dl-riotboard.conf
conf/machine/imx6qdl-pico.conf
conf/machine/imx6qdl-variscite-som.conf
conf/machine/imx6sl-warp.conf
conf/machine/imx6ul-kontron.conf
conf/machine/imx6ul-pico.conf
conf/machine/nitrogen6sx.conf
conf/machine/nitrogen6x-lite.conf
conf/machine/nitrogen6x.conf
conf/machine/nitrogen8m.conf
conf/machine/nitrogen8mm.conf
conf/machine/nitrogen8mn.conf
conf/machine/nitrogen8mp.conf
conf/machine/ventana.conf
conf/machine/wandboard.conf

We reworked the SoC overrides so we avoids duplication and redundancy;
machines affected are:
- apalis-imx6
- colibri-imx6
- colibri-imx6ull
- cubox-i
- imx6dl-riotboard
- imx6qdl-pico
- imx6qdl-variscite-som
- imx6sl-warp
- imx6ul-kontron
- imx6ul-pico
- nitrogen6sx
- nitrogen6x-lite
- nitrogen6x
- ventana
- wandboard
- nitrogen8m
- nitrogen8mm
- nitrogen8mn
- nitrogen8mp
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

Rework machine definitions to reduce duplication

---

conf/machine/nitrogen6sx.conf
conf/machine/nitrogen6x-lite.conf
conf/machine/nitrogen6x.conf
conf/machine/nitrogen7.conf
conf/machine/nitrogen8m.conf
conf/machine/nitrogen8mm.conf
conf/machine/nitrogen8mn.conf
conf/machine/nitrogen8mp.conf

This PR is an improved version of PR #205
-Fixes errors due to new BSP overrides syntax;
-Drop unnecessary code.
This PR was tested on `nitrogen8m` using `core-image-base` image.

Fix nitrogen8 boards

---

recipes-kernel/linux-firmware/linux-firmware_%.bbappend

linux-firmware: Use nonarch_base_libdir instead of hardcoding /lib

---

conf/machine/apalis-imx6.conf
conf/machine/colibri-imx6.conf
conf/machine/colibri-imx6ull.conf
conf/machine/colibri-imx7-emmc.conf
conf/machine/colibri-imx7-nand.conf
conf/machine/colibri-vf.conf
conf/machine/nitrogen8m.conf
conf/machine/nitrogen8mm.conf
conf/machine/nitrogen8mn.conf
conf/machine/nitrogen8mp.conf

With OE core commit [1c90b27d2c](https://github.com/openembedded/openembedded-core/commit/1c90b27d2c65cfb4f9debf0272820b6a95942f76) ("kernel: make kernel-base recommend kernel-image, not depend") the way the kernel is deployed into the rootfs silently changed, i.e. there is no build or run time error/warning that the kernel binary is deployed despite one did not want it. 
Note that commit 1c90b27d2c is already in the kirkstone branch.
@gibsson I run my sed script over all files in the layers. So the nitrogen machines would be updated by this commit too. Hope you approve, otherwise I will rewrite the commit.

machines: follow kernel deployment changes

---

recipes-kernel/linux/linux-boundary_5.4.bb

Linux version 5.4.110. Latest and greatest 5.4 kernel (5.4 2.2.0 branch
was obsolete).

linux-boundary: bump version to 5.4 2.3.0

---

conf/machine/colibri-imx6.conf

Some users might want to change u-boot-default-script preferred
provider, so let's use a soft assignment for that.
Signed-off-by: Sergio Prado <sergio.prado@toradex.com>

colibri-imx6: use soft assignment for u-boot-default-script provider

---

recipes-bsp/imx-atf/imx-atf-boundary_2.3.bb

imx-boot was updated to copy a binary from different path, so need to
fix.

imx-atf-boundary: update do_deploy to fix binary path as per imx-boot

---

recipes-kernel/linux/linux-boundary_5.10.bb

Changelog:
- update to 5.10.104
- most notably fixes issue with suspend/resume functionality

linux-boundary: bump revision to e236955f

---

recipes-kernel/linux/linux-kontron_5.4.bb

Bump kernel to e2057e52d version

linux-kontron: Bump kernel to e2057e52d version

---

recipes-bsp/u-boot/u-boot-kontron_2020.01.bb

This change includes the following commits:
- 1e797797ee4 kontron_mx6ul: Read second mac address from fuses
- e53e9c23ee3 imx: imx8mm: kontron: Use new LPDDR4 config parameters
- 9ecc52dde47 imx: imx8mm: kontron: Remove 100mt DDR setpoint
- 7629f16df68 imx: imx8mm: kontron: lpddr4_timing.c: Add spaces for proper alignment
- 9aa5a039b36 clk: imx8mm: fix clk set parent
- eb5a1eb17ce arm64: dts: imx8mm: correct assigned clocks for FEC
- 4456d7f8a6a Fix previous commit and add missing status property for i2c2
- a7626e58983 imx: imx8mm: kontron: Add support for PMIC PCA9450
- 367b3fc5799 power: pmic: add SPL_DM_PMIC_PCA9450 symbol to Kconfig
- 461e97938f0 pca9450a: fix i2c address
- 240d3ec16a4 power: pmic_pca9450: fix PCA9450A I2C address
- 8218729034b power: Add new PMIC PCA9450 driver
- …

u-boot-kontron: Bump u-boot revision to 1e797797

---

recipes-kernel/linux/linux-boundary_5.15.bb

Linux Version 5.15.52.
Signed-off-by: Chris Dimich <chris.dimich@boundarydevices.com>

linux-boundary: bump revision to 45abf648

---

recipes-kernel/linux/linux-boundary_5.10.bb

Mainly to support more custom device tree mods.

linux-boundary: bump revision to 87ebd8b0

---

recipes-bsp/u-boot/u-boot-boundary-common_2020.10.inc

Main updates are:
- Support KSZ PHY update for latest board rev
- Better display support (both MIPI & HDMI)
- Add preboot command support
- Add gzip bmp display support
- Add erase env command

u-boot-boundary: bump revision to 181aa1693e1

---

recipes-bsp/imx-atf/imx-atf-boundary_2.6.bb

Based upon NXP lf-6.1.1-1.0.0 branch.

imx-atf-boundary: bump version to 2.6

---

conf/machine/nitrogen8m.conf
conf/machine/nitrogen8mm.conf
conf/machine/nitrogen8mn.conf
conf/machine/nitrogen8mp.conf

@chrisdimich 
This would cleanup the machine if https://github.com/Freescale/meta-freescale/pull/1488 should goes in
With that pull request the imx-boot-container override would no longer be used anywhere. imx-boot would be provided for all i.MX 8Mx machines by U-Boot, (for i.MX8X and i.MX8QM it stays with the imx-boot recipe).

nitrogen8m...: remove obsolete imx-boot-container override

---

conf/machine/nitrogen8mm.conf
conf/machine/nitrogen8mn.conf
conf/machine/nitrogen8mp.conf
recipes-kernel/linux/linux-boundary_5.15.bb

This series cleans up the configurations to include all the necessary dtb and remove the one not matching the architecture.
It also updates the kernel to the latest version.
Would need to be back-ported to kirkstone.

boundary: update kernel + cleanup

---

recipes-kernel/linux/linux-boundary_5.15.bb

To support Cypress based Wifi and BT modules such as the LWB5+.

linux-boundary: bump revision to d4a57b30

---

conf/layer.conf

Main meta-freescale layer is compatible and can also be used with OE kirkstone, so follow the same change as this layer is mostly an extra to the main layer.

conf/layer.conf: add back compatibility to kirkstone

---

recipes-kernel/linux/linux-boundary_6.1.bb

Will print as:
6.1.22+yocto+g46a61156410f

linux-boundary: fix LOCALVERSION

---

recipes-kernel/linux/linux-boundary_5.15.bb

To support Rev10 of Nitrogen8M Plus SMARC.

linux-boundary: bump revision to 0adfddbb

---

recipes-kernel/linux/linux-boundary_5.4.bb

dunfell: linux-boundary: bump revision to 416a208

---

recipes-kernel/linux/linux-boundary_5.4.bb

gatesgarth: linux-boundary: bump revision to 416a208

---

recipes-kernel/linux/linux-boundary_5.10.bb

Mainly to support changes to PHY and audio.

honister: linux-boundary: bump revision to a0ec9916

---

recipes-kernel/linux/linux-boundary_6.1.bb

Master: linux-boundary: bump revision to ba56160e

---

recipes-kernel/linux/linux-boundary_5.15.bb

Kirkstone: linux-boundary: bump revision to 0d2e8ff2

---

conf/machine/include/imx233-olinuxino.inc
conf/machine/wandboard.conf

The 32-bit ARM device trees in the Linux kernel were reorganized in a manner similar to how the 64-bit ARM device trees have always been organized: by placing them in vendor+family subdirectories. Therefore update the KERNEL_DEVICETREE definitions to match.

ARM 32-bit device-tree reorganization

---

recipes-bsp/imx-atf/imx-atf-boundary_2.8.bb

imx-atf-boundary: update to boundary-lf-6.1.22-2.0.0

---

recipes-kernel/linux/linux-boundary_6.1.bb

Mainly for Nitrogen 8M Mini SMARC fixes.

Master: linux-boundary: bump revision to 2ada7473

---

recipes-kernel/linux/linux-boundary_6.1.bb

Mainly for nitrogen93 and nitrogen8ulp fixes.

linux-boundary: bump revision to 7a916058

---

conf/machine/olimex-imx8mp-evb.conf
recipes-kernel/linux/linux-fslc-imx/0001-imx8mp-olimex.dts-Olimex-iMX8MP-SOM-EVB-IND.patch

This Github pull request provides improvements for the Olimex i.MX8MP board:
* linux-fslc-imx: Update imx8mp-olimex.dts patch for kernel 6.6. Align it with imx8mp-evk.dts and apply the same changes on top of it as for kernel lf-5.10.y-1.0.0 provided by Olimex in their builtroot repository: https://github.com/OLIMEX/buildroot-imx/commit/fcf7064d442075c204168eaff8e92883ed7bf9e8
* olimex-imx8mp-evb.conf: Explicitly set UBOOT_DTB_NAME to imx8mp-evk.dtb and use this dtb for U-Boot.
Tested with `core-image-base` branch master on Olimex iMX8MP-SOM-EVB-IND

Olimex i.MX8MP Improvements

---

recipes-bsp/u-boot/u-boot-imx/0001-Add-Olimex-iMX8MP-SOM-EVB-IND.patch

Update the u-boot-imx for Olimex iMX8MP-SOM-EVB-IND to the tag lf-6.6.23-2.0.0, that is used in the NXP BSP LF6.6.23_2.0.0.

u-boot-imx_%.bbappend: Olimex iMX8MP-SOM-EVB-IND

---

recipes-bsp/broadcom-nvram-config/broadcom-nvram-config.inc
recipes-bsp/u-boot/u-boot-script-qoriq_2019.10.bb
recipes-bsp/u-boot/u-boot-script-toradex_2020.07.bb
recipes-core/net-persistent-mac/net-persistent-mac.bb
recipes-kernel/linux-firmware/linux-firmware_%.bbappend
recipes-kernel/linux/linux-fslc_%.bbappend

Update a few recipes to use UNPACKDIR instead of WORKDIR directly. This fixes building against newer master openembedded-core, at least for the wandboard machine.

Fix issues with the UNPACKDIR transition

---

recipes-kernel/linux/linux-boundary_5.15.bb

Changelog:
51c8fea5875f gpu: drm: panel: sn65dsi83: mask clock irq
bb32f223a52d arm64: dts: imx8mp-mmr: Initial device-tree
4a267a5e2661 arm: imx8mm-nitrogen_smarc: enable usb otg support
f528b26ca34a arm: dts: imx8mm-nitrogen_smarc: disable adma for SDIO wifi

linux-boundary: bump rev to 51c8fea5875f

---

recipes-bsp/atf/qoriq-atf_1.5.bb
recipes-bsp/u-boot/u-boot-qoriq_2019.10.bb

Since OE bitbake commit 24772dd2ae6c ("parse/ConfHandler: Add warning for deprecated whitespace usage"), the current build generates the following warning (as example):
| WARNING: .../meta-freescale-3rdparty/recipes-bsp/atf/qoriq-atf_1.5.bb:34 has a lack
| of whitespace around the assignment: 'export CROSS_COMPILE="${TARGET_PREFIX}"'
Fix all the warnings.

recipes: fix whitespace warnings
